/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  interviewSidebar: [
    {
      type: 'autogenerated',
      dirName: 'knowledge-system'
    }
  ],
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'webpack系列',
      items: [
        {
          type: 'autogenerated',
          dirName: 'webpack-tutorial'
        }
      ],
      link: {
        type: 'generated-index',
        title: 'webpack 学习笔记',
        description:
          '涵盖了 webpack4.0 零基础到实战，是慕课网课程的学习笔记 https://coding.imooc.com/class/chapter/316.html#Anchor',
        slug: '/index/webpack-guides',
        keywords: ['webpack']
      }
    },
    {
      type: 'category',
      label: 'React组件库系列',
      items: [
        {
          type: 'autogenerated',
          dirName: 'react-components'
        }
      ],
      link: {
        type: 'generated-index',
        title: 'React 组件库搭建',
        description: '记录了关于组件库搭建的相关知识点及每个组件的编写思路',
        slug: '/index/react-component-guides',
        keywords: ['react', 'components', '组件库']
      }
    },
    {
      type: 'category',
      label: '博客搭建系列',
      items: [
        {
          type: 'autogenerated',
          dirName: 'blog-guides'
        }
      ],
      link: {
        type: 'generated-index',
        title: '博客搭建系列',
        description:
          '包含了所有我曾经使用过的博客工具及其相关教程，包括 Hexo, Next.js, Docusaurus。',
        slug: '/index/blog-guides',
        keywords: ['Docusaurus', 'Next.js', 'Docusaurus']
      }
    },
    {
      type: 'category',
      label: '源码系列',
      items: [
        {
          type: 'autogenerated',
          dirName: 'source-analysis'
        }
      ],
      link: {
        type: 'generated-index',
        title: '源码实现系列',
        description: '记录了一些库的简单实现原理',
        slug: '/index/simple-source',
        keywords: ['event emitter']
      }
    }
  ]
};

module.exports = sidebars;
