/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  interviewSidebar: [
    {
      type: 'autogenerated',
      dirName: '面试总结'
    }
  ],
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'webpack系列',
      items: [
        {
          type: 'autogenerated',
          dirName: 'webpack-tutorial'
        }
      ]
    },
    {
      type: 'category',
      label: 'React组件库系列',
      items: [
        {
          type: 'autogenerated',
          dirName: 'react-components'
        }
      ]
    },
    {
      type: 'category',
      label: '博客搭建系列',
      items: [
        {
          type: 'autogenerated',
          dirName: '博客搭建系列'
        }
      ]
    }
  ]
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
