name: 添加友链
description: 添加你的友链信息
title: "[友链添加]: "
labels: ["friend-link"]
assignees:
  - 3Alan
body:
  - type: input
    id: title
    attributes:
      label: 标题
    validations:
      required: true
  - type: input
    id: avatar
    attributes:
      label: 头像
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: 网站地址
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: 网站描述
    validations:
      required: true
